version: '3'
services:
  lili:
    build:
      context: .
      args:
        - http_proxy=${PROXY}
        - https_proxy=${PROXY}
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_SERVER=mongodb:27017
      # TODO: remove hardcode ip
      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
  # TODO: how to avoid run init accidentally
  init_mongodb:
    build: ./init_mongodb
    volumes:
      - ./init_mongodb:/data/init_mongodb
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_SERVER=mongodb:27017
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    command: mongod --smallfiles --bind_ip_all
    ports:
      - "27017:27017"
volumes:
  data: