version: '3'
services:
  lili:
    build:
      context: ../..
      dockerfile: examples/lili/Dockerfile
      args:
        - http_proxy=${PROXY}
        - https_proxy=${PROXY}
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./config.yaml:/data/config.yaml
    environment:
      - MONGO_SERVER=mongodb:27017
      - CONFIG_PATH=/data/config.yaml
      - LILI_PREFETCH_ALL_DEALS=${LILI_PREFETCH_ALL_DEALS}
      - LILI_MODE=${LILI_MODE}
      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
    restart: always
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    command: mongod --smallfiles --bind_ip_all
    ports:
      - "27017:27017"
    restart: always
  script:
    image: mongo
    volumes:
      - ./mongodump:/tmp/mongodump
      - ./scripts:/tmp/mongo-scripts
    environment:
      - MONGO_SERVER=mongodb:27017
    links:
      - mongodb
    depends_on:
      - mongodb
    working_dir: /tmp/mongo-scripts
    entrypoint: /tmp/mongo-scripts/main.sh
volumes:
  data:
